name: unit tests

on: ["push", "pull_request"]

jobs:
  test:
    env: { UV_SYSTEM_PYTHON: true }
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12", "pypy3.8", "pypy3.9", "pypy3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -r pyproject.toml . pytest pytest-asyncio --all-extras
      - name: Run pytest
        run: |
          pytest -v
          uv pip install "pydantic<2"
          pytest -v
